"""give products a brand and an image

Revision ID: 0002_product_media
Revises: 0001_catalogue
Create Date: 2026-08-22 05:44:33.825538

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002_product_media"
down_revision: str | None = "0001_catalogue"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("brand", sa.String(length=120), nullable=True))
    op.add_column("products", sa.Column("image_url", sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "image_url")
    op.drop_column("products", "brand")
    # ### end Alembic commands ###
